$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1410434447224.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"85360d7ccaf24fccaf16fb109fbb59bc",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0ef7ebac4ad14c9696edb058449da9bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":220,
              "height":970}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91220ec6fc0145d9bfb4a86b6cacd642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":220,
                  "height":970}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"e17e84ede2e8497294498eb0db1b58e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18e5613b60143ea958d7363314ab716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"2f7f707c44dd4d64a845964f1edc1d23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1400,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e4ae80516ed4f0184e2cf81cc5bc278",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1400,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"b752bd86fcf54cd68a2c3e116483cf1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece05dfb2161409dbd91ab5d317a2c7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"418933314d9a4dedb5350017e744cb70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":349},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab10138ec8f64fa888de81d6df6a025b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":349},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 上传",
                      "target":{
                        "targetType":"page",
                        "url":"上传.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"d8f41c2d77074494b77abcec773f922b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":398},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ebe14d86bc44a79fc7981e86f10f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":398},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 查看",
                      "target":{
                        "targetType":"page",
                        "url":"查看.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u10.png"}},
{
          "id":"6db38618e33249d293f5e4ca8ad5fbdf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":496},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c97bc8072e784f08a0243efbc145abe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":496},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 反馈",
                      "target":{
                        "targetType":"page",
                        "url":"反馈.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u12.png"}},
{
          "id":"0fa50479c18644898b45e121abbedf64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":447},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650970c71393492b8a4694e7f0a64001",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":447},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 更新",
                      "target":{
                        "targetType":"page",
                        "url":"更新.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u14.png"}},
{
          "id":"0c828d545e644263a00938bfb8406287",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u16_line.png"}},
{
          "id":"a641d2f0d111492f93924076bb842d5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66cf7fe6a69e4992a8dd24734b829cdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u17.png"}},
{
          "id":"e1d53df9b44d444d871f93e47d09f6a4",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":410,
              "y":273},
            "size":{
              "width":500,
              "height":213}},
          "adaptiveStyles":{
}},
{
          "id":"4ef12c23892f45baad567b636a298b99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":865},
            "size":{
              "width":1400,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ea13b2c03504c2f8533b45b09fb2573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":865},
                "size":{
                  "width":1400,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"a06381af35b04c50818c17384d47fb54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1260,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"545487d72ed644d9bd6115f5ab650e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1260,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0ef7ebac4ad14c9696edb058449da9bc":{
      "scriptId":"u0"},
    "91220ec6fc0145d9bfb4a86b6cacd642":{
      "scriptId":"u1"},
    "e17e84ede2e8497294498eb0db1b58e6":{
      "scriptId":"u2"},
    "a18e5613b60143ea958d7363314ab716":{
      "scriptId":"u3"},
    "2f7f707c44dd4d64a845964f1edc1d23":{
      "scriptId":"u4"},
    "1e4ae80516ed4f0184e2cf81cc5bc278":{
      "scriptId":"u5"},
    "b752bd86fcf54cd68a2c3e116483cf1a":{
      "scriptId":"u6"},
    "ece05dfb2161409dbd91ab5d317a2c7e":{
      "scriptId":"u7"},
    "418933314d9a4dedb5350017e744cb70":{
      "scriptId":"u8"},
    "ab10138ec8f64fa888de81d6df6a025b":{
      "scriptId":"u9"},
    "d8f41c2d77074494b77abcec773f922b":{
      "scriptId":"u10"},
    "b1ebe14d86bc44a79fc7981e86f10f48":{
      "scriptId":"u11"},
    "6db38618e33249d293f5e4ca8ad5fbdf":{
      "scriptId":"u12"},
    "c97bc8072e784f08a0243efbc145abe3":{
      "scriptId":"u13"},
    "0fa50479c18644898b45e121abbedf64":{
      "scriptId":"u14"},
    "650970c71393492b8a4694e7f0a64001":{
      "scriptId":"u15"},
    "0c828d545e644263a00938bfb8406287":{
      "scriptId":"u16"},
    "a641d2f0d111492f93924076bb842d5e":{
      "scriptId":"u17"},
    "66cf7fe6a69e4992a8dd24734b829cdd":{
      "scriptId":"u18"},
    "e1d53df9b44d444d871f93e47d09f6a4":{
      "scriptId":"u19"},
    "4ef12c23892f45baad567b636a298b99":{
      "scriptId":"u20"},
    "3ea13b2c03504c2f8533b45b09fb2573":{
      "scriptId":"u21"},
    "a06381af35b04c50818c17384d47fb54":{
      "scriptId":"u22"},
    "545487d72ed644d9bd6115f5ab650e40":{
      "scriptId":"u23"}}});