$axure.loadCurrentPage({
  "url":"主页（更多）.html",
  "generationDate":new Date(1408832926015.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f0586f7c6a5541c783fd4c2e63d8b06c",
    "type":"Axure:Page",
    "name":"主页（更多）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"238bce7a61bf4c1eafd188be81792c5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":50},
            "size":{
              "width":290,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"445793a7fe6049b0ad6164b42471efac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":50},
                "size":{
                  "width":290,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页的副本/u0.jpg"}},
{
          "id":"ab8d288ba2df4ab6b8b4b8e5d20015be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":290,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6bbea0b1df4b1aaa155931c4e1492e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":290,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页（更多）/u2.jpg"}},
{
          "id":"82aac35352a64bb594b8a7a8ce26a07e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":178,
              "y":470},
            "size":{
              "width":62,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a1c5d6ac1a4e1282c98fd456fa95a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":178,
                  "y":470},
                "size":{
                  "width":62,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 更多-说明",
                      "target":{
                        "targetType":"page",
                        "url":"更多-说明.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"935cd8689c58440bbc3e810e04c997cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":178,
              "y":500},
            "size":{
              "width":62,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"801f05f6b82d4dcebc6648db9e955ab9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":178,
                  "y":500},
                "size":{
                  "width":62,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 更多-分享",
                      "target":{
                        "targetType":"page",
                        "url":"更多-分享.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd8a2b40668945f29b005884ccb191c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":178,
              "y":530},
            "size":{
              "width":62,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5fafdc92d44732b9ff01b50035fa71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":178,
                  "y":530},
                "size":{
                  "width":62,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 更多-反馈",
                      "target":{
                        "targetType":"page",
                        "url":"更多-反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "238bce7a61bf4c1eafd188be81792c5e":{
      "scriptId":"u0"},
    "445793a7fe6049b0ad6164b42471efac":{
      "scriptId":"u1"},
    "ab8d288ba2df4ab6b8b4b8e5d20015be":{
      "scriptId":"u2"},
    "8d6bbea0b1df4b1aaa155931c4e1492e":{
      "scriptId":"u3"},
    "82aac35352a64bb594b8a7a8ce26a07e":{
      "scriptId":"u4"},
    "86a1c5d6ac1a4e1282c98fd456fa95a5":{
      "scriptId":"u5"},
    "935cd8689c58440bbc3e810e04c997cd":{
      "scriptId":"u6"},
    "801f05f6b82d4dcebc6648db9e955ab9":{
      "scriptId":"u7"},
    "cd8a2b40668945f29b005884ccb191c2":{
      "scriptId":"u8"},
    "ce5fafdc92d44732b9ff01b50035fa71":{
      "scriptId":"u9"}}});