$axure.loadCurrentPage({
  "url":"查看.html",
  "generationDate":new Date(1410434447454.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f50cd62eca134ce294db939d3b7d3fc9",
    "type":"Axure:Page",
    "name":"查看",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98b036bf1e9349a49696af1a5e735190",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":220,
              "height":970}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0cc2a291b9841108b8c080eb2d8ea80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":220,
                  "height":970}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"0469ffad43af44eabb90af0ad12732ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e13cb252aa4ca884a91d5276fec8c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"a5b31039982341dab8b687633abe3ce2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1400,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9803cb3855d445a6b93de2895c75f1a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1400,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"9475110a264549eea965eb32618357ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a802b18208433c8e1255b04b8ff38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"630aa48b306344d0a897e5146d333443",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":349},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bff5f3a86bf5421c9c47f313863aaf02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":349},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"acbbe73a78d243ac92528600c692ff6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":398},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc82ac24828d458493440d7e7e8ed9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":398},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.png"}},
{
          "id":"fa02fcc93edf490dbff790effd58fdab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":496},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e56c36f087449bd950420f93575f9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":496},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u12.png"}},
{
          "id":"2665948239234ee7b88105265ee51884",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":447},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4946b4a4813446caa8e5eef19b144471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":447},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u14.png"}},
{
          "id":"77b3e0a181054600b467e6e49b87c1e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u16_line.png"}},
{
          "id":"655c93a64f324dffae021dd0bdcca6df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36b5a7f4b424ce4870faf0e128d4c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u17.png"}},
{
          "id":"0340def505a54cd1b7015b4b177799d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":865},
            "size":{
              "width":1400,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2309fb04a51243deb7cb4b1178704e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":865},
                "size":{
                  "width":1400,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"0b204b2b0c144d7a88e3c466b3a26e8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1260,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"136b7598aa7145c9bdb56a0cf7ab56fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1260,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u21.png"}},
{
          "id":"7bae350844644a8fbd6075c00fc6c759",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":390},
            "size":{
              "width":570,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d3324815ea34090885243be0eea3e6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e358efe61ea43d8bf8898815547a8c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"afe34b19ac3b49a88c0b8de4aadeb833",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"927b06cc2857460aa7dd3112920614b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"dad5a9bf55854c2bb7c82864582d8a90",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"608e2473072b45c5a8c922b6aa25cfc2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u36.png"}},
{
              "id":"8efcb291329440bf9cc9ce190807997c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a4c945b27ab4441ad985960bb4bc5b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"63ea4345b19c4767b407a128369e01a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e2ecc1f5d1648fbbe699dbe45583c19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"ff3f2d08eb304cabb567254ecba1b485",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fea3692fcd4744bba56cf37895a0747e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u36.png"}},
{
              "id":"b53b747d791145ab8bf96642146ae809",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"866b045136c449cc8e4b41b2394bf959",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u28.png"}},
{
              "id":"c27fb12a460e4fd18083c30c1c7e5669",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d031ede329a143cfaabc8c6dccd57e9d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u28.png"}},
{
              "id":"b2669d9d556c4c34a25461fe65379691",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e658e50017e46f6ae8ebbca7a2f1969",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u40.png"}}]},
{
          "id":"847e1b0115eb485c9226c66f7d6d88b4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":390},
            "size":{
              "width":300,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a9416c8d8c1429e90882a0944320e8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4cea21468c464c9e8995d2ddf004099e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"de905e78b7aa403088fdc7e29c368b5f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da2d66d9643f427bbc9504a1c115627d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"552c43511f2347e0b9d28b92f3f13240",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78ea4eb8b1c24f05830e5ad72d14eb83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u55.png"}},
{
              "id":"273432e9a57e409d8546a526d1f8b6ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5648ac74c67d4cb5822084e14e4864ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"a1a83992c68549f4ace4f1c5dd607d9d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3eff53f87d24319a7ef69fa6a706128",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"657e4452137344ee9e164ce836b5ea9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"084393ed376947e182f6b68eb948f106",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u55.png"}},
{
              "id":"4dfb570c806e4da79dbfa241867aa18d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30b103ba93a44e97945813d537335920",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u47.png"}},
{
              "id":"d9a7db7a538a4ea6b29047da1cc83185",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21b268fa3eee45e28f222a46a843f1cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u47.png"}},
{
              "id":"2a4e9e6aec054b90b3eb70faa1d0f952",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac63bc31c80d4c75b40d69a390bfe9f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u59.png"}}]},
{
          "id":"be28567320e84c488bfd132417457662",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":424},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba571b00ba8451abf027b72a66b851f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":424},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u61.png"}},
{
          "id":"61c70a00a4c24a52acab6ccbdce61596",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1122,
              "y":466},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f44586ece414dcdba45a0281b69f85a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1122,
                  "y":466},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u61.png"}},
{
          "id":"58037770bcbe41e0a1a92e95bcb49622",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":422},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dec517d358646669b8da6180ac156ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":422},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u65.png"}},
{
          "id":"647fc728dd324cf8b35b89f2ec87e2eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":466},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e90474ae51e44b7bc2e21729c6a41da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":466},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u65.png"}},
{
          "id":"39e948ee0f6d40c8b61b8a97bc4e4c1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":250,
              "y":284},
            "size":{
              "width":332,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f36092c2d24478693a9781bf180ff16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":284},
                "size":{
                  "width":332,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "98b036bf1e9349a49696af1a5e735190":{
      "scriptId":"u0"},
    "d0cc2a291b9841108b8c080eb2d8ea80":{
      "scriptId":"u1"},
    "0469ffad43af44eabb90af0ad12732ea":{
      "scriptId":"u2"},
    "91e13cb252aa4ca884a91d5276fec8c1":{
      "scriptId":"u3"},
    "a5b31039982341dab8b687633abe3ce2":{
      "scriptId":"u4"},
    "9803cb3855d445a6b93de2895c75f1a8":{
      "scriptId":"u5"},
    "9475110a264549eea965eb32618357ce":{
      "scriptId":"u6"},
    "07a802b18208433c8e1255b04b8ff38f":{
      "scriptId":"u7"},
    "630aa48b306344d0a897e5146d333443":{
      "scriptId":"u8"},
    "bff5f3a86bf5421c9c47f313863aaf02":{
      "scriptId":"u9"},
    "acbbe73a78d243ac92528600c692ff6e":{
      "scriptId":"u10"},
    "bc82ac24828d458493440d7e7e8ed9c4":{
      "scriptId":"u11"},
    "fa02fcc93edf490dbff790effd58fdab":{
      "scriptId":"u12"},
    "4e56c36f087449bd950420f93575f9ef":{
      "scriptId":"u13"},
    "2665948239234ee7b88105265ee51884":{
      "scriptId":"u14"},
    "4946b4a4813446caa8e5eef19b144471":{
      "scriptId":"u15"},
    "77b3e0a181054600b467e6e49b87c1e4":{
      "scriptId":"u16"},
    "655c93a64f324dffae021dd0bdcca6df":{
      "scriptId":"u17"},
    "d36b5a7f4b424ce4870faf0e128d4c0d":{
      "scriptId":"u18"},
    "0340def505a54cd1b7015b4b177799d4":{
      "scriptId":"u19"},
    "2309fb04a51243deb7cb4b1178704e39":{
      "scriptId":"u20"},
    "0b204b2b0c144d7a88e3c466b3a26e8c":{
      "scriptId":"u21"},
    "136b7598aa7145c9bdb56a0cf7ab56fd":{
      "scriptId":"u22"},
    "7bae350844644a8fbd6075c00fc6c759":{
      "scriptId":"u23"},
    "6d3324815ea34090885243be0eea3e6b":{
      "scriptId":"u24"},
    "1e358efe61ea43d8bf8898815547a8c3":{
      "scriptId":"u25"},
    "8efcb291329440bf9cc9ce190807997c":{
      "scriptId":"u26"},
    "7a4c945b27ab4441ad985960bb4bc5b1":{
      "scriptId":"u27"},
    "b53b747d791145ab8bf96642146ae809":{
      "scriptId":"u28"},
    "866b045136c449cc8e4b41b2394bf959":{
      "scriptId":"u29"},
    "afe34b19ac3b49a88c0b8de4aadeb833":{
      "scriptId":"u30"},
    "927b06cc2857460aa7dd3112920614b9":{
      "scriptId":"u31"},
    "63ea4345b19c4767b407a128369e01a5":{
      "scriptId":"u32"},
    "1e2ecc1f5d1648fbbe699dbe45583c19":{
      "scriptId":"u33"},
    "c27fb12a460e4fd18083c30c1c7e5669":{
      "scriptId":"u34"},
    "d031ede329a143cfaabc8c6dccd57e9d":{
      "scriptId":"u35"},
    "dad5a9bf55854c2bb7c82864582d8a90":{
      "scriptId":"u36"},
    "608e2473072b45c5a8c922b6aa25cfc2":{
      "scriptId":"u37"},
    "ff3f2d08eb304cabb567254ecba1b485":{
      "scriptId":"u38"},
    "fea3692fcd4744bba56cf37895a0747e":{
      "scriptId":"u39"},
    "b2669d9d556c4c34a25461fe65379691":{
      "scriptId":"u40"},
    "3e658e50017e46f6ae8ebbca7a2f1969":{
      "scriptId":"u41"},
    "847e1b0115eb485c9226c66f7d6d88b4":{
      "scriptId":"u42"},
    "7a9416c8d8c1429e90882a0944320e8a":{
      "scriptId":"u43"},
    "4cea21468c464c9e8995d2ddf004099e":{
      "scriptId":"u44"},
    "273432e9a57e409d8546a526d1f8b6ab":{
      "scriptId":"u45"},
    "5648ac74c67d4cb5822084e14e4864ce":{
      "scriptId":"u46"},
    "4dfb570c806e4da79dbfa241867aa18d":{
      "scriptId":"u47"},
    "30b103ba93a44e97945813d537335920":{
      "scriptId":"u48"},
    "de905e78b7aa403088fdc7e29c368b5f":{
      "scriptId":"u49"},
    "da2d66d9643f427bbc9504a1c115627d":{
      "scriptId":"u50"},
    "a1a83992c68549f4ace4f1c5dd607d9d":{
      "scriptId":"u51"},
    "e3eff53f87d24319a7ef69fa6a706128":{
      "scriptId":"u52"},
    "d9a7db7a538a4ea6b29047da1cc83185":{
      "scriptId":"u53"},
    "21b268fa3eee45e28f222a46a843f1cc":{
      "scriptId":"u54"},
    "552c43511f2347e0b9d28b92f3f13240":{
      "scriptId":"u55"},
    "78ea4eb8b1c24f05830e5ad72d14eb83":{
      "scriptId":"u56"},
    "657e4452137344ee9e164ce836b5ea9b":{
      "scriptId":"u57"},
    "084393ed376947e182f6b68eb948f106":{
      "scriptId":"u58"},
    "2a4e9e6aec054b90b3eb70faa1d0f952":{
      "scriptId":"u59"},
    "ac63bc31c80d4c75b40d69a390bfe9f6":{
      "scriptId":"u60"},
    "be28567320e84c488bfd132417457662":{
      "scriptId":"u61"},
    "1ba571b00ba8451abf027b72a66b851f":{
      "scriptId":"u62"},
    "61c70a00a4c24a52acab6ccbdce61596":{
      "scriptId":"u63"},
    "2f44586ece414dcdba45a0281b69f85a":{
      "scriptId":"u64"},
    "58037770bcbe41e0a1a92e95bcb49622":{
      "scriptId":"u65"},
    "0dec517d358646669b8da6180ac156ec":{
      "scriptId":"u66"},
    "647fc728dd324cf8b35b89f2ec87e2eb":{
      "scriptId":"u67"},
    "5e90474ae51e44b7bc2e21729c6a41da":{
      "scriptId":"u68"},
    "39e948ee0f6d40c8b61b8a97bc4e4c1a":{
      "scriptId":"u69"},
    "0f36092c2d24478693a9781bf180ff16":{
      "scriptId":"u70"}}});