$axure.loadCurrentPage({
  "url":"帮助中心.html",
  "generationDate":new Date(1408818771218.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9f52696fb47c4b9896d2ebfb90e5dc93",
    "type":"Axure:Page",
    "name":"帮助中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25b1462295f148aea67f7dd9745368d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1263,
              "height":808}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ef5fad869c4316a5b2c337c808a255",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1263,
                  "height":808}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助中心/u0.jpg"}},
{
          "id":"9a5da67522454cd9ab5dd851683f9945",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":808},
            "size":{
              "width":1262,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd6704ba99c24a0fa2fd8afa91a43674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":808},
                "size":{
                  "width":1262,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.jpg"}},
{
          "id":"079a2e82a7bd426fb886425af6f54206",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":480,
              "y":0},
            "size":{
              "width":90,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e2a0883d19f4d74b5b1514dc91da7e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":480,
                  "y":0},
                "size":{
                  "width":90,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a11212ed1ca4cd18a8913041d04b8a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":601,
              "y":10},
            "size":{
              "width":72,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0d003d21540468aab1fbc356827be37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":601,
                  "y":10},
                "size":{
                  "width":72,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 更新日志",
                      "target":{
                        "targetType":"page",
                        "url":"更新日志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b40f0e4398f342378e71870cbc7385ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":799,
              "y":10},
            "size":{
              "width":52,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8167cdee5d34f58ae0757f609b28393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":799,
                  "y":10},
                "size":{
                  "width":52,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 反馈",
                      "target":{
                        "targetType":"page",
                        "url":"反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "25b1462295f148aea67f7dd9745368d2":{
      "scriptId":"u0"},
    "91ef5fad869c4316a5b2c337c808a255":{
      "scriptId":"u1"},
    "9a5da67522454cd9ab5dd851683f9945":{
      "scriptId":"u2"},
    "dd6704ba99c24a0fa2fd8afa91a43674":{
      "scriptId":"u3"},
    "079a2e82a7bd426fb886425af6f54206":{
      "scriptId":"u4"},
    "3e2a0883d19f4d74b5b1514dc91da7e8":{
      "scriptId":"u5"},
    "9a11212ed1ca4cd18a8913041d04b8a2":{
      "scriptId":"u6"},
    "e0d003d21540468aab1fbc356827be37":{
      "scriptId":"u7"},
    "b40f0e4398f342378e71870cbc7385ad":{
      "scriptId":"u8"},
    "a8167cdee5d34f58ae0757f609b28393":{
      "scriptId":"u9"}}});