$axure.loadCurrentPage({
  "url":"更新日志.html",
  "generationDate":new Date(1408818771062.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4e92dcccb5c749d5a42dfe83da43f2a0",
    "type":"Axure:Page",
    "name":"更新日志",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"22d2a24a869e4fbe87b1e1856d21c640",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1264,
              "height":275}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec9b80b74164430ebaca626200aef30b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1264,
                  "height":275}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新日志/u0.jpg"}},
{
          "id":"34100e30c68649e0aa0d68bcb1b6e2f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":270},
            "size":{
              "width":1260,
              "height":534}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"123b6a6cfe2a43968a40e6cc990cb3fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":1260,
                  "height":534}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新日志/u2.jpg"}},
{
          "id":"bc8a4867f23b4a4c93694604d7c9cef3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-2,
              "y":804},
            "size":{
              "width":1262,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb19445da373402c97c0524962f0aff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-2,
                  "y":804},
                "size":{
                  "width":1262,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.jpg"}},
{
          "id":"a23e882f72414be296c5f9d410f6456e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":488,
              "y":0},
            "size":{
              "width":82,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693f3e0081144a66b7fbde55b37b33ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":488,
                  "y":0},
                "size":{
                  "width":82,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b14ffabdcbe4076b35d7ddceb43ac75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":720,
              "y":10},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd981c9b9c34e17a1f6d9f157279a93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":720,
                  "y":10},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帮助中心",
                      "target":{
                        "targetType":"page",
                        "url":"帮助中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85fa2d28e5f84cf3bf237e818a8f1da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":808,
              "y":10},
            "size":{
              "width":52,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93d790832e0440eb830b342b3575be70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":808,
                  "y":10},
                "size":{
                  "width":52,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 反馈",
                      "target":{
                        "targetType":"page",
                        "url":"反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "22d2a24a869e4fbe87b1e1856d21c640":{
      "scriptId":"u0"},
    "ec9b80b74164430ebaca626200aef30b":{
      "scriptId":"u1"},
    "34100e30c68649e0aa0d68bcb1b6e2f6":{
      "scriptId":"u2"},
    "123b6a6cfe2a43968a40e6cc990cb3fd":{
      "scriptId":"u3"},
    "bc8a4867f23b4a4c93694604d7c9cef3":{
      "scriptId":"u4"},
    "eb19445da373402c97c0524962f0aff3":{
      "scriptId":"u5"},
    "a23e882f72414be296c5f9d410f6456e":{
      "scriptId":"u6"},
    "693f3e0081144a66b7fbde55b37b33ea":{
      "scriptId":"u7"},
    "7b14ffabdcbe4076b35d7ddceb43ac75":{
      "scriptId":"u8"},
    "4fd981c9b9c34e17a1f6d9f157279a93":{
      "scriptId":"u9"},
    "85fa2d28e5f84cf3bf237e818a8f1da3":{
      "scriptId":"u10"},
    "93d790832e0440eb830b342b3575be70":{
      "scriptId":"u11"}}});