$axure.loadCurrentPage({
  "url":"上传.html",
  "generationDate":new Date(1410434447298.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2c3630856f9641898feb3c47e74a176b",
    "type":"Axure:Page",
    "name":"上传",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98b036bf1e9349a49696af1a5e735190",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":220,
              "height":970}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0cc2a291b9841108b8c080eb2d8ea80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":220,
                  "height":970}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"0469ffad43af44eabb90af0ad12732ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e13cb252aa4ca884a91d5276fec8c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"a5b31039982341dab8b687633abe3ce2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1400,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9803cb3855d445a6b93de2895c75f1a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1400,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"9475110a264549eea965eb32618357ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a802b18208433c8e1255b04b8ff38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"630aa48b306344d0a897e5146d333443",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":349},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bff5f3a86bf5421c9c47f313863aaf02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":349},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"acbbe73a78d243ac92528600c692ff6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":398},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc82ac24828d458493440d7e7e8ed9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":398},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 查看",
                      "target":{
                        "targetType":"page",
                        "url":"查看.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u10.png"}},
{
          "id":"fa02fcc93edf490dbff790effd58fdab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":496},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e56c36f087449bd950420f93575f9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":496},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 反馈",
                      "target":{
                        "targetType":"page",
                        "url":"反馈.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u12.png"}},
{
          "id":"2665948239234ee7b88105265ee51884",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":447},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4946b4a4813446caa8e5eef19b144471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":447},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 更新",
                      "target":{
                        "targetType":"page",
                        "url":"更新.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u14.png"}},
{
          "id":"77b3e0a181054600b467e6e49b87c1e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u16_line.png"}},
{
          "id":"655c93a64f324dffae021dd0bdcca6df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36b5a7f4b424ce4870faf0e128d4c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u17.png"}},
{
          "id":"0340def505a54cd1b7015b4b177799d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":865},
            "size":{
              "width":1400,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2309fb04a51243deb7cb4b1178704e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":865},
                "size":{
                  "width":1400,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"9c33b50181114e409cc744ae29874f1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1260,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"827b92c2d11b4f0f9afedbb968911075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1260,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传/u21.png"}},
{
          "id":"16b73d1a843241fdbc6d27a291931394",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":298,
              "y":367},
            "size":{
              "width":142,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81862b91bbc04a72a0cfaf58cc144cad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":298,
                  "y":367},
                "size":{
                  "width":142,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b882794d6b4746a49d11211405dbf639",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":367},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000}]}]}},
          "tabbable":true},
{
          "id":"37dbdbc346b848279126d20412f91d79",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":366},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"293b51403523465a807b26253671bca8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":412},
            "size":{
              "width":70,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b02513b1235641b3b9e3aa009d1c2d5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":412},
                "size":{
                  "width":70,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 http://www.baidu.com",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://www.baidu.com",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/上传/u27.png"}},
{
          "id":"46e3b2b70c6c40eda5fbe45b1456e483",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":299,
              "y":430},
            "size":{
              "width":142,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ef65a0152d46e7a785b99c25069b00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":299,
                  "y":430},
                "size":{
                  "width":142,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdd32a7f744c45478a7f2c2f1fbe164a",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":531},
            "size":{
              "width":340,
              "height":61}},
          "adaptiveStyles":{
}},
{
          "id":"cc4b531066114e2ca7aa966f721e190f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":250,
              "y":284},
            "size":{
              "width":332,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b709568cbedb489cb719a71de3061cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":284},
                "size":{
                  "width":332,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "98b036bf1e9349a49696af1a5e735190":{
      "scriptId":"u0"},
    "d0cc2a291b9841108b8c080eb2d8ea80":{
      "scriptId":"u1"},
    "0469ffad43af44eabb90af0ad12732ea":{
      "scriptId":"u2"},
    "91e13cb252aa4ca884a91d5276fec8c1":{
      "scriptId":"u3"},
    "a5b31039982341dab8b687633abe3ce2":{
      "scriptId":"u4"},
    "9803cb3855d445a6b93de2895c75f1a8":{
      "scriptId":"u5"},
    "9475110a264549eea965eb32618357ce":{
      "scriptId":"u6"},
    "07a802b18208433c8e1255b04b8ff38f":{
      "scriptId":"u7"},
    "630aa48b306344d0a897e5146d333443":{
      "scriptId":"u8"},
    "bff5f3a86bf5421c9c47f313863aaf02":{
      "scriptId":"u9"},
    "acbbe73a78d243ac92528600c692ff6e":{
      "scriptId":"u10"},
    "bc82ac24828d458493440d7e7e8ed9c4":{
      "scriptId":"u11"},
    "fa02fcc93edf490dbff790effd58fdab":{
      "scriptId":"u12"},
    "4e56c36f087449bd950420f93575f9ef":{
      "scriptId":"u13"},
    "2665948239234ee7b88105265ee51884":{
      "scriptId":"u14"},
    "4946b4a4813446caa8e5eef19b144471":{
      "scriptId":"u15"},
    "77b3e0a181054600b467e6e49b87c1e4":{
      "scriptId":"u16"},
    "655c93a64f324dffae021dd0bdcca6df":{
      "scriptId":"u17"},
    "d36b5a7f4b424ce4870faf0e128d4c0d":{
      "scriptId":"u18"},
    "0340def505a54cd1b7015b4b177799d4":{
      "scriptId":"u19"},
    "2309fb04a51243deb7cb4b1178704e39":{
      "scriptId":"u20"},
    "9c33b50181114e409cc744ae29874f1f":{
      "scriptId":"u21"},
    "827b92c2d11b4f0f9afedbb968911075":{
      "scriptId":"u22"},
    "16b73d1a843241fdbc6d27a291931394":{
      "scriptId":"u23"},
    "81862b91bbc04a72a0cfaf58cc144cad":{
      "scriptId":"u24"},
    "b882794d6b4746a49d11211405dbf639":{
      "scriptId":"u25"},
    "37dbdbc346b848279126d20412f91d79":{
      "scriptId":"u26"},
    "293b51403523465a807b26253671bca8":{
      "scriptId":"u27"},
    "b02513b1235641b3b9e3aa009d1c2d5a":{
      "scriptId":"u28"},
    "46e3b2b70c6c40eda5fbe45b1456e483":{
      "scriptId":"u29"},
    "23ef65a0152d46e7a785b99c25069b00":{
      "scriptId":"u30"},
    "fdd32a7f744c45478a7f2c2f1fbe164a":{
      "scriptId":"u31"},
    "cc4b531066114e2ca7aa966f721e190f":{
      "scriptId":"u32"},
    "b709568cbedb489cb719a71de3061cc2":{
      "scriptId":"u33"}}});