$axure.loadCurrentPage({
  "url":"主页（连接成功）.html",
  "generationDate":new Date(1408832925453.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4c60f9a8bd9f4fb3be0bd7d197c89db7",
    "type":"Axure:Page",
    "name":"主页（连接成功）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"238bce7a61bf4c1eafd188be81792c5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":50},
            "size":{
              "width":290,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"445793a7fe6049b0ad6164b42471efac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":50},
                "size":{
                  "width":290,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页的副本/u0.jpg"}},
{
          "id":"4d2a7474091c474c91cf83de2f6a887b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":290,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3f92acbaea8423497ce1779c62bb962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":290,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页（连接成功）/u2.jpg"}},
{
          "id":"e44b6a4288a84d26b0e3bdf8e678b810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900,
              "opacity":0},
            "location":{
              "x":140,
              "y":518},
            "size":{
              "width":42,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54ef192fab324e06bd4064e11732893b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900,
                  "opacity":0},
                "location":{
                  "x":140,
                  "y":518},
                "size":{
                  "width":42,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页（更多）",
                      "target":{
                        "targetType":"page",
                        "url":"主页（更多）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aecc0f8e67e4c70a24d131446931d23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900,
              "opacity":0},
            "location":{
              "x":340,
              "y":273},
            "size":{
              "width":50,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0893c6115004db788de20c80e4e5574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900,
                  "opacity":0},
                "location":{
                  "x":340,
                  "y":273},
                "size":{
                  "width":50,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 游戏手柄",
                      "target":{
                        "targetType":"page",
                        "url":"游戏手柄.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f80770d8f2424958b773b4366b4f073e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900,
              "opacity":0},
            "location":{
              "x":271,
              "y":340},
            "size":{
              "width":50,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff2d9ede0d0a44778e2a5ed28a46e286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900,
                  "opacity":0},
                "location":{
                  "x":271,
                  "y":340},
                "size":{
                  "width":50,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 鼠标键盘",
                      "target":{
                        "targetType":"page",
                        "url":"鼠标键盘.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec6674f272ba4bab8553f573e5643481",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900,
              "opacity":0},
            "location":{
              "x":302,
              "y":411},
            "size":{
              "width":40,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cdf20b6f6364a9dba87368e6cb12f51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900,
                  "opacity":0},
                "location":{
                  "x":302,
                  "y":411},
                "size":{
                  "width":40,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 遥控PPT",
                      "target":{
                        "targetType":"page",
                        "url":"遥控ppt.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7a3816c9b8c4449a5f23839bbeaecbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900,
              "opacity":0},
            "location":{
              "x":379,
              "y":411},
            "size":{
              "width":40,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd700b4e7154b7a8e5acf9f92845c2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900,
                  "opacity":0},
                "location":{
                  "x":379,
                  "y":411},
                "size":{
                  "width":40,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 文件互传",
                      "target":{
                        "targetType":"page",
                        "url":"文件互传.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa143ffc32c34c4ca321223dca1c589d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF9900,
              "opacity":0},
            "location":{
              "x":400,
              "y":328},
            "size":{
              "width":32,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bb286abf7f94affa3c084e0572bccc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF9900,
                  "opacity":0},
                "location":{
                  "x":400,
                  "y":328},
                "size":{
                  "width":32,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 屏幕共享",
                      "target":{
                        "targetType":"page",
                        "url":"屏幕共享.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "238bce7a61bf4c1eafd188be81792c5e":{
      "scriptId":"u0"},
    "445793a7fe6049b0ad6164b42471efac":{
      "scriptId":"u1"},
    "4d2a7474091c474c91cf83de2f6a887b":{
      "scriptId":"u2"},
    "e3f92acbaea8423497ce1779c62bb962":{
      "scriptId":"u3"},
    "e44b6a4288a84d26b0e3bdf8e678b810":{
      "scriptId":"u4"},
    "54ef192fab324e06bd4064e11732893b":{
      "scriptId":"u5"},
    "3aecc0f8e67e4c70a24d131446931d23":{
      "scriptId":"u6"},
    "f0893c6115004db788de20c80e4e5574":{
      "scriptId":"u7"},
    "f80770d8f2424958b773b4366b4f073e":{
      "scriptId":"u8"},
    "ff2d9ede0d0a44778e2a5ed28a46e286":{
      "scriptId":"u9"},
    "ec6674f272ba4bab8553f573e5643481":{
      "scriptId":"u10"},
    "4cdf20b6f6364a9dba87368e6cb12f51":{
      "scriptId":"u11"},
    "d7a3816c9b8c4449a5f23839bbeaecbb":{
      "scriptId":"u12"},
    "5bd700b4e7154b7a8e5acf9f92845c2d":{
      "scriptId":"u13"},
    "fa143ffc32c34c4ca321223dca1c589d":{
      "scriptId":"u14"},
    "6bb286abf7f94affa3c084e0572bccc9":{
      "scriptId":"u15"}}});