$axure.loadCurrentPage({
  "url":"鼠标键盘.html",
  "generationDate":new Date(1408832926625),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"701dfee1286c49f8b968790314fd2092",
    "type":"Axure:Page",
    "name":"鼠标键盘",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"238bce7a61bf4c1eafd188be81792c5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":50},
            "size":{
              "width":290,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"445793a7fe6049b0ad6164b42471efac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":50},
                "size":{
                  "width":290,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页的副本/u0.jpg"}},
{
          "id":"84212d4aa7fa4203b7ecaf512dfe3bca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":290,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d80221e5a87947f0bf207aa7a10672eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":290,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/鼠标键盘/u2.jpg"}},
{
          "id":"953b63a213c146468fc6dcc9587bb54c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":228,
              "y":270},
            "size":{
              "width":112,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ea497bfc074c8ebbda978587521fd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":228,
                  "y":270},
                "size":{
                  "width":112,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57249eabcd6f4eb58d0bedb0b2546077",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":228,
              "y":320},
            "size":{
              "width":112,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9dee6c365694fa5b98dbcd68afa8d2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":228,
                  "y":320},
                "size":{
                  "width":112,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"788a7dbc2c724873a1f689efd104889a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":158,
              "y":270},
            "size":{
              "width":262,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d513c9a2496843638b544ba69752acfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":158,
                  "y":270},
                "size":{
                  "width":262,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 鼠标",
                      "target":{
                        "targetType":"page",
                        "url":"鼠标.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe3219ff90eb47678a4164d97ecf0973",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":150,
              "y":320},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9563cee714ea41e7a203ecdd0a1b8c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":150,
                  "y":320},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 键盘",
                      "target":{
                        "targetType":"page",
                        "url":"键盘.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "238bce7a61bf4c1eafd188be81792c5e":{
      "scriptId":"u0"},
    "445793a7fe6049b0ad6164b42471efac":{
      "scriptId":"u1"},
    "84212d4aa7fa4203b7ecaf512dfe3bca":{
      "scriptId":"u2"},
    "d80221e5a87947f0bf207aa7a10672eb":{
      "scriptId":"u3"},
    "953b63a213c146468fc6dcc9587bb54c":{
      "scriptId":"u4"},
    "79ea497bfc074c8ebbda978587521fd9":{
      "scriptId":"u5"},
    "57249eabcd6f4eb58d0bedb0b2546077":{
      "scriptId":"u6"},
    "f9dee6c365694fa5b98dbcd68afa8d2e":{
      "scriptId":"u7"},
    "788a7dbc2c724873a1f689efd104889a":{
      "scriptId":"u8"},
    "d513c9a2496843638b544ba69752acfc":{
      "scriptId":"u9"},
    "fe3219ff90eb47678a4164d97ecf0973":{
      "scriptId":"u10"},
    "9563cee714ea41e7a203ecdd0a1b8c91":{
      "scriptId":"u11"}}});