$axure.loadCurrentPage({
  "url":"反馈.html",
  "generationDate":new Date(1410434447691.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ed8de6805afb4918b3999940a75ec40e",
    "type":"Axure:Page",
    "name":"反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98b036bf1e9349a49696af1a5e735190",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":220,
              "height":970}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0cc2a291b9841108b8c080eb2d8ea80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":220,
                  "height":970}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"0469ffad43af44eabb90af0ad12732ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e13cb252aa4ca884a91d5276fec8c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"a5b31039982341dab8b687633abe3ce2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1400,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9803cb3855d445a6b93de2895c75f1a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1400,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"9475110a264549eea965eb32618357ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a802b18208433c8e1255b04b8ff38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"630aa48b306344d0a897e5146d333443",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":349},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bff5f3a86bf5421c9c47f313863aaf02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":349},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"acbbe73a78d243ac92528600c692ff6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":398},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc82ac24828d458493440d7e7e8ed9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":398},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.png"}},
{
          "id":"fa02fcc93edf490dbff790effd58fdab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":496},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e56c36f087449bd950420f93575f9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":496},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u12.png"}},
{
          "id":"2665948239234ee7b88105265ee51884",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":447},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4946b4a4813446caa8e5eef19b144471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":447},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u14.png"}},
{
          "id":"77b3e0a181054600b467e6e49b87c1e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u16_line.png"}},
{
          "id":"655c93a64f324dffae021dd0bdcca6df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36b5a7f4b424ce4870faf0e128d4c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u17.png"}},
{
          "id":"0340def505a54cd1b7015b4b177799d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":865},
            "size":{
              "width":1400,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2309fb04a51243deb7cb4b1178704e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":865},
                "size":{
                  "width":1400,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"c1e3bd84f4784dbd8ce05a78057cfc70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1260,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee067d0935f4b16a5d382b76ee956a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1260,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/反馈/u21.png"}},
{
          "id":"249e574643ca4d0eb4bb74a363af1b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":260,
              "y":294},
            "size":{
              "width":332,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7b51ec822f741c7aff1df06625b58f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":294},
                "size":{
                  "width":332,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"466c58e27ee6492382df460539857ef8",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":390},
            "size":{
              "width":570,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2b63e91c3b458681e51b7c00ce0e23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6847266edb974744af38ae92b0c48556",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"df31f415ee5943be9996656b20583da3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa94d3c262364a04a6a74308fdf65bce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"46324ff50ba440b8a35d88d3b31d1d13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f6c2c96dfb34903a92904f934ff1d30",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u36.png"}},
{
              "id":"475ec70028114fd6a63a8337c1ec86b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f46567f5a6d345cf85125d0a145f5dc4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"450c4abbbb75455b85580791f72c94be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bb0d28e5ded4ee0af569580c1ea559e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"b41dca2fffa146d2a8647415f5fa4892",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"003f00841bc04b148551682df3f7422c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u36.png"}},
{
              "id":"725ac5fe767643668d8c3044bf360ef8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"efa8da180baf4b4d9eeec95e4aca2ff1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u28.png"}},
{
              "id":"dc3d815a3b4a446396a123d7d2533439",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cecfd3a4950343178f28a879015271e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u28.png"}},
{
              "id":"338a45c124794f38bc8a833f30c2a2a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1c99932516048deb42857054b90f841",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u40.png"}}]},
{
          "id":"61c72f31308147519216521af1712488",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":390},
            "size":{
              "width":300,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26c0151aac384c42926d72bf77fbd2f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1aff81ffc2504cd19d92da61e919f12a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"c993b564d99b4e4495bb5e1fc732ba8c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56e668cb2131408ea054d344bb3815e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"58e594ed81eb44afa08b9c8e32c7cfaa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a240c4983dae424485d5e105bcef039c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u55.png"}},
{
              "id":"ceb96e35539f4929bf20349354f0e6d7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff8da21e11a14d38af0d5f760ac09a2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"00efddc1eb714077a83fa5060144d03c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5975e6e7b72842fd96044c7734b83a5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"d10eb146baff43d1b10dcd3f345900f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea9b81e7621642949d9b085d3b6f20e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u55.png"}},
{
              "id":"3960f96315554ed9a6f75c273d5dd576",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72fb140be6bb46dfa68afe8518be9f1c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u47.png"}},
{
              "id":"3b96ce400f8a4909acb973f8106eb3df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2304253ff4f4522a07ff410e67a62d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u47.png"}},
{
              "id":"70a73d7c9de54f23a89333a3ebd106f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d1949ffbae394a77be03fa42756debf2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u59.png"}}]},
{
          "id":"a35ee8ba5f8544b7ab520e2d787dc2bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":424},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9452a36eea4829aa61342cefc1aa90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":424},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u61.png"}},
{
          "id":"38f42bbf70954b0694fdec0b3ef8df33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":422},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54085aa93d41405f8f6310fb2ba4e754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":422},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u65.png"}},
{
          "id":"d64eb4e716484933a9757d7c454ec82a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":464},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b290b745d97c4aefbdeaf1ac40bbf4ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":464},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u61.png"}},
{
          "id":"11316dd09d184105b16e8d987ba351ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":462},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c56ae000a4a4a4dbdf2ca30c1c26ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":462},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u65.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "98b036bf1e9349a49696af1a5e735190":{
      "scriptId":"u0"},
    "d0cc2a291b9841108b8c080eb2d8ea80":{
      "scriptId":"u1"},
    "0469ffad43af44eabb90af0ad12732ea":{
      "scriptId":"u2"},
    "91e13cb252aa4ca884a91d5276fec8c1":{
      "scriptId":"u3"},
    "a5b31039982341dab8b687633abe3ce2":{
      "scriptId":"u4"},
    "9803cb3855d445a6b93de2895c75f1a8":{
      "scriptId":"u5"},
    "9475110a264549eea965eb32618357ce":{
      "scriptId":"u6"},
    "07a802b18208433c8e1255b04b8ff38f":{
      "scriptId":"u7"},
    "630aa48b306344d0a897e5146d333443":{
      "scriptId":"u8"},
    "bff5f3a86bf5421c9c47f313863aaf02":{
      "scriptId":"u9"},
    "acbbe73a78d243ac92528600c692ff6e":{
      "scriptId":"u10"},
    "bc82ac24828d458493440d7e7e8ed9c4":{
      "scriptId":"u11"},
    "fa02fcc93edf490dbff790effd58fdab":{
      "scriptId":"u12"},
    "4e56c36f087449bd950420f93575f9ef":{
      "scriptId":"u13"},
    "2665948239234ee7b88105265ee51884":{
      "scriptId":"u14"},
    "4946b4a4813446caa8e5eef19b144471":{
      "scriptId":"u15"},
    "77b3e0a181054600b467e6e49b87c1e4":{
      "scriptId":"u16"},
    "655c93a64f324dffae021dd0bdcca6df":{
      "scriptId":"u17"},
    "d36b5a7f4b424ce4870faf0e128d4c0d":{
      "scriptId":"u18"},
    "0340def505a54cd1b7015b4b177799d4":{
      "scriptId":"u19"},
    "2309fb04a51243deb7cb4b1178704e39":{
      "scriptId":"u20"},
    "c1e3bd84f4784dbd8ce05a78057cfc70":{
      "scriptId":"u21"},
    "6ee067d0935f4b16a5d382b76ee956a9":{
      "scriptId":"u22"},
    "249e574643ca4d0eb4bb74a363af1b04":{
      "scriptId":"u23"},
    "e7b51ec822f741c7aff1df06625b58f5":{
      "scriptId":"u24"},
    "466c58e27ee6492382df460539857ef8":{
      "scriptId":"u25"},
    "8a2b63e91c3b458681e51b7c00ce0e23":{
      "scriptId":"u26"},
    "6847266edb974744af38ae92b0c48556":{
      "scriptId":"u27"},
    "475ec70028114fd6a63a8337c1ec86b7":{
      "scriptId":"u28"},
    "f46567f5a6d345cf85125d0a145f5dc4":{
      "scriptId":"u29"},
    "725ac5fe767643668d8c3044bf360ef8":{
      "scriptId":"u30"},
    "efa8da180baf4b4d9eeec95e4aca2ff1":{
      "scriptId":"u31"},
    "df31f415ee5943be9996656b20583da3":{
      "scriptId":"u32"},
    "fa94d3c262364a04a6a74308fdf65bce":{
      "scriptId":"u33"},
    "450c4abbbb75455b85580791f72c94be":{
      "scriptId":"u34"},
    "9bb0d28e5ded4ee0af569580c1ea559e":{
      "scriptId":"u35"},
    "dc3d815a3b4a446396a123d7d2533439":{
      "scriptId":"u36"},
    "cecfd3a4950343178f28a879015271e2":{
      "scriptId":"u37"},
    "46324ff50ba440b8a35d88d3b31d1d13":{
      "scriptId":"u38"},
    "6f6c2c96dfb34903a92904f934ff1d30":{
      "scriptId":"u39"},
    "b41dca2fffa146d2a8647415f5fa4892":{
      "scriptId":"u40"},
    "003f00841bc04b148551682df3f7422c":{
      "scriptId":"u41"},
    "338a45c124794f38bc8a833f30c2a2a0":{
      "scriptId":"u42"},
    "f1c99932516048deb42857054b90f841":{
      "scriptId":"u43"},
    "61c72f31308147519216521af1712488":{
      "scriptId":"u44"},
    "26c0151aac384c42926d72bf77fbd2f4":{
      "scriptId":"u45"},
    "1aff81ffc2504cd19d92da61e919f12a":{
      "scriptId":"u46"},
    "ceb96e35539f4929bf20349354f0e6d7":{
      "scriptId":"u47"},
    "ff8da21e11a14d38af0d5f760ac09a2d":{
      "scriptId":"u48"},
    "3960f96315554ed9a6f75c273d5dd576":{
      "scriptId":"u49"},
    "72fb140be6bb46dfa68afe8518be9f1c":{
      "scriptId":"u50"},
    "c993b564d99b4e4495bb5e1fc732ba8c":{
      "scriptId":"u51"},
    "56e668cb2131408ea054d344bb3815e6":{
      "scriptId":"u52"},
    "00efddc1eb714077a83fa5060144d03c":{
      "scriptId":"u53"},
    "5975e6e7b72842fd96044c7734b83a5b":{
      "scriptId":"u54"},
    "3b96ce400f8a4909acb973f8106eb3df":{
      "scriptId":"u55"},
    "a2304253ff4f4522a07ff410e67a62d7":{
      "scriptId":"u56"},
    "58e594ed81eb44afa08b9c8e32c7cfaa":{
      "scriptId":"u57"},
    "a240c4983dae424485d5e105bcef039c":{
      "scriptId":"u58"},
    "d10eb146baff43d1b10dcd3f345900f6":{
      "scriptId":"u59"},
    "ea9b81e7621642949d9b085d3b6f20e2":{
      "scriptId":"u60"},
    "70a73d7c9de54f23a89333a3ebd106f4":{
      "scriptId":"u61"},
    "d1949ffbae394a77be03fa42756debf2":{
      "scriptId":"u62"},
    "a35ee8ba5f8544b7ab520e2d787dc2bc":{
      "scriptId":"u63"},
    "ca9452a36eea4829aa61342cefc1aa90":{
      "scriptId":"u64"},
    "38f42bbf70954b0694fdec0b3ef8df33":{
      "scriptId":"u65"},
    "54085aa93d41405f8f6310fb2ba4e754":{
      "scriptId":"u66"},
    "d64eb4e716484933a9757d7c454ec82a":{
      "scriptId":"u67"},
    "b290b745d97c4aefbdeaf1ac40bbf4ad":{
      "scriptId":"u68"},
    "11316dd09d184105b16e8d987ba351ea":{
      "scriptId":"u69"},
    "9c56ae000a4a4a4dbdf2ca30c1c26ad3":{
      "scriptId":"u70"}}});