$axure.loadCurrentPage({
  "url":"播放-暂停.html",
  "generationDate":new Date(1408832925000),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4c0523135768450795fd8138a2885d6c",
    "type":"Axure:Page",
    "name":"播放-暂停",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"238bce7a61bf4c1eafd188be81792c5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":50},
            "size":{
              "width":290,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"445793a7fe6049b0ad6164b42471efac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":50},
                "size":{
                  "width":290,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页的副本/u0.jpg"}},
{
          "id":"c78c9402b8db48eaa4641b4669861a17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":70},
            "size":{
              "width":290,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b84e658872548c1bcbbd65c1fce6d9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":70},
                "size":{
                  "width":290,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/播放-暂停/u2.jpg"}},
{
          "id":"8c46b12d84bb49fabba6a287b7ef288c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":230,
              "y":260},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e65cdbf8842e406aa88029bf6ebdef7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":230,
                  "y":260},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 播放-开始",
                      "target":{
                        "targetType":"page",
                        "url":"播放-开始.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddcf410770834e9786b7a3e9abf1afb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":140,
              "y":534},
            "size":{
              "width":70,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ef8b05603147d48988f68d221d9fb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":140,
                  "y":534},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页（连接成功）",
                      "target":{
                        "targetType":"page",
                        "url":"主页（连接成功）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "238bce7a61bf4c1eafd188be81792c5e":{
      "scriptId":"u0"},
    "445793a7fe6049b0ad6164b42471efac":{
      "scriptId":"u1"},
    "c78c9402b8db48eaa4641b4669861a17":{
      "scriptId":"u2"},
    "9b84e658872548c1bcbbd65c1fce6d9c":{
      "scriptId":"u3"},
    "8c46b12d84bb49fabba6a287b7ef288c":{
      "scriptId":"u4"},
    "e65cdbf8842e406aa88029bf6ebdef7a":{
      "scriptId":"u5"},
    "ddcf410770834e9786b7a3e9abf1afb8":{
      "scriptId":"u6"},
    "d1ef8b05603147d48988f68d221d9fb3":{
      "scriptId":"u7"}}});