$axure.loadCurrentPage({
  "url":"反馈.html",
  "generationDate":new Date(1408818770937.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"968fe5e55e854c699217a8fa29367968",
    "type":"Axure:Page",
    "name":"反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5f19872a3afc45829649757060af6b14",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1279,
              "height":738}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b8eaddb987947ac9b78a7c82f83c384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1279,
                  "height":738}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/反馈/u0.jpg"}},
{
          "id":"8911ea8bebe1495a939ce513c970790b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":663},
            "size":{
              "width":1265,
              "height":357}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e04b92192b15450b8f5f3f3fd7cd0ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":663},
                "size":{
                  "width":1265,
                  "height":357}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/反馈/u2.jpg"}},
{
          "id":"aa4a056bc2c846849b869802e8c86c09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":150,
              "y":874},
            "size":{
              "width":80,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca538c2c2a3419a8a290911f8148617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":150,
                  "y":874},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5f19872a3afc45829649757060af6b14":{
      "scriptId":"u0"},
    "2b8eaddb987947ac9b78a7c82f83c384":{
      "scriptId":"u1"},
    "8911ea8bebe1495a939ce513c970790b":{
      "scriptId":"u2"},
    "e04b92192b15450b8f5f3f3fd7cd0ba2":{
      "scriptId":"u3"},
    "aa4a056bc2c846849b869802e8c86c09":{
      "scriptId":"u4"},
    "cca538c2c2a3419a8a290911f8148617":{
      "scriptId":"u5"}}});