$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1408818770765.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e88b61b034cc4f50ae21d91729f6383c",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6032a78f9e2243c38cc53d9110e7a15c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1260,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa30f94f2e114ddb8f51e1c7cdeb3752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1260,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.jpg"}},
{
          "id":"35a5ae8e33e8485ebf178f54fcdd33d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":640},
            "size":{
              "width":1263,
              "height":239}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24fe4ab7355741799287b47c56b60c49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":640},
                "size":{
                  "width":1263,
                  "height":239}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.jpg"}},
{
          "id":"b60ecc845a7942fdaed96f838fb3ded0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1170},
            "size":{
              "width":1265,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"564bf7a9c43e478e87e995125ebb28e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1170},
                "size":{
                  "width":1265,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.jpg"}},
{
          "id":"e0b0311fd7714bff86e4843a6a75bfee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":872},
            "size":{
              "width":1264,
              "height":298}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc8c50043e344caf88733074815996f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":872},
                "size":{
                  "width":1264,
                  "height":298}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.jpg"}},
{
          "id":"76e0d07a8e6f44b592d9c69b0eaae4ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-13,
              "y":1423},
            "size":{
              "width":1263,
              "height":277}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77e6d82a19e74738a26f245ce49d6e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-13,
                  "y":1423},
                "size":{
                  "width":1263,
                  "height":277}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.jpg"}},
{
          "id":"c9a202848db448ff9f568e6d5efb727c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1700},
            "size":{
              "width":1262,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5af2d8bc27a64d299cfb0fa0bd040017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1700},
                "size":{
                  "width":1262,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.jpg"}},
{
          "id":"eea5bb4439d84f028af3df14264b1ec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":308,
              "y":494},
            "size":{
              "width":292,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f3f3cfee95748baa2908f6098e9325f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":308,
                  "y":494},
                "size":{
                  "width":292,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 下载-电脑",
                      "target":{
                        "targetType":"page",
                        "url":"下载-电脑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"790a259e12ac40a9b19a244a1c2bc788",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":678,
              "y":494},
            "size":{
              "width":292,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82b0ca4949f741b48d3a71d87196d857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":678,
                  "y":494},
                "size":{
                  "width":292,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 下载-手机",
                      "target":{
                        "targetType":"page",
                        "url":"下载-手机.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90c0e4b082334de28b0a3c65c05ac402",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":548,
              "y":10},
            "size":{
              "width":72,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb65e81406094b658adecf50cb045771",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":548,
                  "y":10},
                "size":{
                  "width":72,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 更新日志",
                      "target":{
                        "targetType":"page",
                        "url":"更新日志.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e13bbcb7018b4ebd8aaca4628d88d2cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":640,
              "y":10},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54d64db417314e1abfc9b9bf63aef30e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":640,
                  "y":10},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帮助中心",
                      "target":{
                        "targetType":"page",
                        "url":"帮助中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"566c5b5a7d5e44e0b5085c1504b6f5f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":738,
              "y":10},
            "size":{
              "width":52,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed55137fb96f45eea330232b57a6d738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":738,
                  "y":10},
                "size":{
                  "width":52,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 反馈",
                      "target":{
                        "targetType":"page",
                        "url":"反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6032a78f9e2243c38cc53d9110e7a15c":{
      "scriptId":"u0"},
    "aa30f94f2e114ddb8f51e1c7cdeb3752":{
      "scriptId":"u1"},
    "35a5ae8e33e8485ebf178f54fcdd33d4":{
      "scriptId":"u2"},
    "24fe4ab7355741799287b47c56b60c49":{
      "scriptId":"u3"},
    "b60ecc845a7942fdaed96f838fb3ded0":{
      "scriptId":"u4"},
    "564bf7a9c43e478e87e995125ebb28e4":{
      "scriptId":"u5"},
    "e0b0311fd7714bff86e4843a6a75bfee":{
      "scriptId":"u6"},
    "dc8c50043e344caf88733074815996f1":{
      "scriptId":"u7"},
    "76e0d07a8e6f44b592d9c69b0eaae4ee":{
      "scriptId":"u8"},
    "77e6d82a19e74738a26f245ce49d6e07":{
      "scriptId":"u9"},
    "c9a202848db448ff9f568e6d5efb727c":{
      "scriptId":"u10"},
    "5af2d8bc27a64d299cfb0fa0bd040017":{
      "scriptId":"u11"},
    "eea5bb4439d84f028af3df14264b1ec3":{
      "scriptId":"u12"},
    "8f3f3cfee95748baa2908f6098e9325f":{
      "scriptId":"u13"},
    "790a259e12ac40a9b19a244a1c2bc788":{
      "scriptId":"u14"},
    "82b0ca4949f741b48d3a71d87196d857":{
      "scriptId":"u15"},
    "90c0e4b082334de28b0a3c65c05ac402":{
      "scriptId":"u16"},
    "bb65e81406094b658adecf50cb045771":{
      "scriptId":"u17"},
    "e13bbcb7018b4ebd8aaca4628d88d2cd":{
      "scriptId":"u18"},
    "54d64db417314e1abfc9b9bf63aef30e":{
      "scriptId":"u19"},
    "566c5b5a7d5e44e0b5085c1504b6f5f8":{
      "scriptId":"u20"},
    "ed55137fb96f45eea330232b57a6d738":{
      "scriptId":"u21"}}});