$axure.loadCurrentPage({
  "url":"更新.html",
  "generationDate":new Date(1410434447577.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"383a80eca4a94d02ba87a42a3d29314f",
    "type":"Axure:Page",
    "name":"更新",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98b036bf1e9349a49696af1a5e735190",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":220,
              "height":970}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0cc2a291b9841108b8c080eb2d8ea80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":220,
                  "height":970}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"0469ffad43af44eabb90af0ad12732ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e13cb252aa4ca884a91d5276fec8c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"a5b31039982341dab8b687633abe3ce2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1400,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9803cb3855d445a6b93de2895c75f1a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1400,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"9475110a264549eea965eb32618357ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":300},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a802b18208433c8e1255b04b8ff38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":300},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"630aa48b306344d0a897e5146d333443",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":349},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bff5f3a86bf5421c9c47f313863aaf02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":349},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"acbbe73a78d243ac92528600c692ff6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":398},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc82ac24828d458493440d7e7e8ed9c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":398},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.png"}},
{
          "id":"fa02fcc93edf490dbff790effd58fdab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":496},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e56c36f087449bd950420f93575f9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":496},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u12.png"}},
{
          "id":"2665948239234ee7b88105265ee51884",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":447},
            "size":{
              "width":220,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4946b4a4813446caa8e5eef19b144471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":447},
                "size":{
                  "width":220,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u14.png"}},
{
          "id":"77b3e0a181054600b467e6e49b87c1e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":119},
            "size":{
              "width":1400,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u16_line.png"}},
{
          "id":"655c93a64f324dffae021dd0bdcca6df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-1},
            "size":{
              "width":1400,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d36b5a7f4b424ce4870faf0e128d4c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":1400,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u17.png"}},
{
          "id":"0340def505a54cd1b7015b4b177799d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":865},
            "size":{
              "width":1400,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2309fb04a51243deb7cb4b1178704e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":865},
                "size":{
                  "width":1400,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.png"}},
{
          "id":"1b4f3e6e6793413384725ecd184097a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":128},
            "size":{
              "width":1260,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c813ee1d124499b9ccaac0ecb6d6ad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":128},
                "size":{
                  "width":1260,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新/u21.png"}},
{
          "id":"a34b072b80104927a404756dca1241d3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":390},
            "size":{
              "width":570,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05e5693056084463a7efaa7dd8d5a719",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06dd4d0d3f6d4b0d85dedfacefee2fff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"8d00da6ba0444dcbb42a9d27483ae945",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45ad171298a0496db76ca46957b81bc4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"a37e44a41dc14db8bd90debe66089c45",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da4dd6fea92e430e864e28c19aab326a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u36.png"}},
{
              "id":"75efef3d2c58438b8cff2252129708ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f99c36fcdb44b81b1c1e320f9bf6c61",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"4266db1383f44c5f9fe3fa50bce79dca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3eb2e5877c3242ae945dafd0843a5439",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u24.png"}},
{
              "id":"2067a0a877c54333867ae233bf001f7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":190,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f7049a07699404687f52736c44b7913",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":190,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u36.png"}},
{
              "id":"bca18a9d2a094945bc1ef9995325664e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2e843fab58440649ae37095541f4c33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u28.png"}},
{
              "id":"62370229724e4f7f9e712d0430095b24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18205d11b7bc4a80ae0bb19186967ef0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u28.png"}},
{
              "id":"76ae35a7a50b45bfb5408331795343e0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":380,
                  "y":60},
                "size":{
                  "width":190,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a073a3568584614baa3513ed2490b30",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":380,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u40.png"}}]},
{
          "id":"2f37fe9af8244e87aa7b1ffbd7863c16",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":390},
            "size":{
              "width":300,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c653bb49b74bb5b31620f97b434f94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2c6baefcc0d471e97ce1f2f1b8f70db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"0b902f54c7a3460eba6747d5193659c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"830ceaf0301a4b91ba7d2dc6e47f04c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"48ab32d8937c4ea194e50e3647f8287f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dcbf97ac2bf4e35ae95f54324b9174a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u55.png"}},
{
              "id":"ad11093922b74b2e84b39a60a5175160",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"862da56272ac4443a0ece9032522b06b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"849f6062dbdb4d138fa173cf6380256f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c4850c355b04f4aa7d2d108b0dffae5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u43.png"}},
{
              "id":"26fcb1fedb684edca24bee1bbff9ebac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ff5ecb3a63840bb981dd33f099c8d21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u55.png"}},
{
              "id":"7b8dc0a86f934c76af7c056dede1acf1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e5cb20b529b4cfe8d52fa061ed09068",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u47.png"}},
{
              "id":"2b6c9f7ecd3944e79b1dc193c898ddb7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83f969e7ea244a4eb0ae6e208c628118",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u47.png"}},
{
              "id":"7651b58565014b33acd97794193847bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a0bf94788ea4d4f840dc668bf3ec033",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看/u59.png"}}]},
{
          "id":"f6fdb7814ad546858411c38b82d50e9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":260,
              "y":294},
            "size":{
              "width":332,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb959b67584145c4909a3f9b346abea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":294},
                "size":{
                  "width":332,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc8579484f3640388b2f43e73effc900",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":265,
              "y":559},
            "size":{
              "width":425,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c7c016b5e634992abb31a931d939b1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":559},
                "size":{
                  "width":425,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"782aa2059d664cf0816f753147bfdb72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":424},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"473bf8aa45fc4f289ed05b1458eeafdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":424},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u61.png"}},
{
          "id":"be3f654d405c498596bb7a4001443fa8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":422},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff896a1742d6478ebed2cdfaed4cbf5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":422},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u65.png"}},
{
          "id":"b259d754b4e0437d91cc3690b7cc2bb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":464},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9d8059449f74ec9a1c6b1e6382fe75e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":464},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u61.png"}},
{
          "id":"328885da361b4c6e9b1d8ab30345ffe9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1028,
              "y":462},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"707e093cf6bb468988822ca137badf2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1028,
                  "y":462},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看/u65.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "98b036bf1e9349a49696af1a5e735190":{
      "scriptId":"u0"},
    "d0cc2a291b9841108b8c080eb2d8ea80":{
      "scriptId":"u1"},
    "0469ffad43af44eabb90af0ad12732ea":{
      "scriptId":"u2"},
    "91e13cb252aa4ca884a91d5276fec8c1":{
      "scriptId":"u3"},
    "a5b31039982341dab8b687633abe3ce2":{
      "scriptId":"u4"},
    "9803cb3855d445a6b93de2895c75f1a8":{
      "scriptId":"u5"},
    "9475110a264549eea965eb32618357ce":{
      "scriptId":"u6"},
    "07a802b18208433c8e1255b04b8ff38f":{
      "scriptId":"u7"},
    "630aa48b306344d0a897e5146d333443":{
      "scriptId":"u8"},
    "bff5f3a86bf5421c9c47f313863aaf02":{
      "scriptId":"u9"},
    "acbbe73a78d243ac92528600c692ff6e":{
      "scriptId":"u10"},
    "bc82ac24828d458493440d7e7e8ed9c4":{
      "scriptId":"u11"},
    "fa02fcc93edf490dbff790effd58fdab":{
      "scriptId":"u12"},
    "4e56c36f087449bd950420f93575f9ef":{
      "scriptId":"u13"},
    "2665948239234ee7b88105265ee51884":{
      "scriptId":"u14"},
    "4946b4a4813446caa8e5eef19b144471":{
      "scriptId":"u15"},
    "77b3e0a181054600b467e6e49b87c1e4":{
      "scriptId":"u16"},
    "655c93a64f324dffae021dd0bdcca6df":{
      "scriptId":"u17"},
    "d36b5a7f4b424ce4870faf0e128d4c0d":{
      "scriptId":"u18"},
    "0340def505a54cd1b7015b4b177799d4":{
      "scriptId":"u19"},
    "2309fb04a51243deb7cb4b1178704e39":{
      "scriptId":"u20"},
    "1b4f3e6e6793413384725ecd184097a1":{
      "scriptId":"u21"},
    "2c813ee1d124499b9ccaac0ecb6d6ad8":{
      "scriptId":"u22"},
    "a34b072b80104927a404756dca1241d3":{
      "scriptId":"u23"},
    "05e5693056084463a7efaa7dd8d5a719":{
      "scriptId":"u24"},
    "06dd4d0d3f6d4b0d85dedfacefee2fff":{
      "scriptId":"u25"},
    "75efef3d2c58438b8cff2252129708ac":{
      "scriptId":"u26"},
    "2f99c36fcdb44b81b1c1e320f9bf6c61":{
      "scriptId":"u27"},
    "bca18a9d2a094945bc1ef9995325664e":{
      "scriptId":"u28"},
    "a2e843fab58440649ae37095541f4c33":{
      "scriptId":"u29"},
    "8d00da6ba0444dcbb42a9d27483ae945":{
      "scriptId":"u30"},
    "45ad171298a0496db76ca46957b81bc4":{
      "scriptId":"u31"},
    "4266db1383f44c5f9fe3fa50bce79dca":{
      "scriptId":"u32"},
    "3eb2e5877c3242ae945dafd0843a5439":{
      "scriptId":"u33"},
    "62370229724e4f7f9e712d0430095b24":{
      "scriptId":"u34"},
    "18205d11b7bc4a80ae0bb19186967ef0":{
      "scriptId":"u35"},
    "a37e44a41dc14db8bd90debe66089c45":{
      "scriptId":"u36"},
    "da4dd6fea92e430e864e28c19aab326a":{
      "scriptId":"u37"},
    "2067a0a877c54333867ae233bf001f7d":{
      "scriptId":"u38"},
    "6f7049a07699404687f52736c44b7913":{
      "scriptId":"u39"},
    "76ae35a7a50b45bfb5408331795343e0":{
      "scriptId":"u40"},
    "6a073a3568584614baa3513ed2490b30":{
      "scriptId":"u41"},
    "2f37fe9af8244e87aa7b1ffbd7863c16":{
      "scriptId":"u42"},
    "b2c653bb49b74bb5b31620f97b434f94":{
      "scriptId":"u43"},
    "c2c6baefcc0d471e97ce1f2f1b8f70db":{
      "scriptId":"u44"},
    "ad11093922b74b2e84b39a60a5175160":{
      "scriptId":"u45"},
    "862da56272ac4443a0ece9032522b06b":{
      "scriptId":"u46"},
    "7b8dc0a86f934c76af7c056dede1acf1":{
      "scriptId":"u47"},
    "4e5cb20b529b4cfe8d52fa061ed09068":{
      "scriptId":"u48"},
    "0b902f54c7a3460eba6747d5193659c6":{
      "scriptId":"u49"},
    "830ceaf0301a4b91ba7d2dc6e47f04c6":{
      "scriptId":"u50"},
    "849f6062dbdb4d138fa173cf6380256f":{
      "scriptId":"u51"},
    "7c4850c355b04f4aa7d2d108b0dffae5":{
      "scriptId":"u52"},
    "2b6c9f7ecd3944e79b1dc193c898ddb7":{
      "scriptId":"u53"},
    "83f969e7ea244a4eb0ae6e208c628118":{
      "scriptId":"u54"},
    "48ab32d8937c4ea194e50e3647f8287f":{
      "scriptId":"u55"},
    "6dcbf97ac2bf4e35ae95f54324b9174a":{
      "scriptId":"u56"},
    "26fcb1fedb684edca24bee1bbff9ebac":{
      "scriptId":"u57"},
    "8ff5ecb3a63840bb981dd33f099c8d21":{
      "scriptId":"u58"},
    "7651b58565014b33acd97794193847bf":{
      "scriptId":"u59"},
    "7a0bf94788ea4d4f840dc668bf3ec033":{
      "scriptId":"u60"},
    "f6fdb7814ad546858411c38b82d50e9a":{
      "scriptId":"u61"},
    "cb959b67584145c4909a3f9b346abea8":{
      "scriptId":"u62"},
    "dc8579484f3640388b2f43e73effc900":{
      "scriptId":"u63"},
    "3c7c016b5e634992abb31a931d939b1b":{
      "scriptId":"u64"},
    "782aa2059d664cf0816f753147bfdb72":{
      "scriptId":"u65"},
    "473bf8aa45fc4f289ed05b1458eeafdb":{
      "scriptId":"u66"},
    "be3f654d405c498596bb7a4001443fa8":{
      "scriptId":"u67"},
    "ff896a1742d6478ebed2cdfaed4cbf5d":{
      "scriptId":"u68"},
    "b259d754b4e0437d91cc3690b7cc2bb3":{
      "scriptId":"u69"},
    "e9d8059449f74ec9a1c6b1e6382fe75e":{
      "scriptId":"u70"},
    "328885da361b4c6e9b1d8ab30345ffe9":{
      "scriptId":"u71"},
    "707e093cf6bb468988822ca137badf2e":{
      "scriptId":"u72"}}});