$axure.loadCurrentPage({
  "url":"下载-电脑.html",
  "generationDate":new Date(1408818770875),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"08b9ffaeb79f4743a8e211d2b4ab7441",
    "type":"Axure:Page",
    "name":"下载-电脑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6032a78f9e2243c38cc53d9110e7a15c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1260,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa30f94f2e114ddb8f51e1c7cdeb3752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1260,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.jpg"}},
{
          "id":"35a5ae8e33e8485ebf178f54fcdd33d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":640},
            "size":{
              "width":1263,
              "height":239}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24fe4ab7355741799287b47c56b60c49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":640},
                "size":{
                  "width":1263,
                  "height":239}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.jpg"}},
{
          "id":"b60ecc845a7942fdaed96f838fb3ded0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1170},
            "size":{
              "width":1265,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"564bf7a9c43e478e87e995125ebb28e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1170},
                "size":{
                  "width":1265,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.jpg"}},
{
          "id":"e0b0311fd7714bff86e4843a6a75bfee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":872},
            "size":{
              "width":1264,
              "height":298}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc8c50043e344caf88733074815996f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":872},
                "size":{
                  "width":1264,
                  "height":298}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.jpg"}},
{
          "id":"76e0d07a8e6f44b592d9c69b0eaae4ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-13,
              "y":1423},
            "size":{
              "width":1263,
              "height":277}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77e6d82a19e74738a26f245ce49d6e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-13,
                  "y":1423},
                "size":{
                  "width":1263,
                  "height":277}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.jpg"}},
{
          "id":"c9a202848db448ff9f568e6d5efb727c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1700},
            "size":{
              "width":1262,
              "height":355}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5af2d8bc27a64d299cfb0fa0bd040017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1700},
                "size":{
                  "width":1262,
                  "height":355}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.jpg"}},
{
          "id":"c9ee3800379847d0b413cad1837a9d43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":230},
            "size":{
              "width":490,
              "height":233}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc964ace8fb4cc7b5902ab4a374aaa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":230},
                "size":{
                  "width":490,
                  "height":233}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下载-电脑/u12.jpg"}},
{
          "id":"0aced7d1953c4746a1439aa1bb129bc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x333333,
              "opacity":0},
            "location":{
              "x":385,
              "y":230},
            "size":{
              "width":490,
              "height":233}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db056f410b884218bc7deab4fdb31f7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x333333,
                  "opacity":0},
                "location":{
                  "x":385,
                  "y":230},
                "size":{
                  "width":490,
                  "height":233}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6032a78f9e2243c38cc53d9110e7a15c":{
      "scriptId":"u0"},
    "aa30f94f2e114ddb8f51e1c7cdeb3752":{
      "scriptId":"u1"},
    "35a5ae8e33e8485ebf178f54fcdd33d4":{
      "scriptId":"u2"},
    "24fe4ab7355741799287b47c56b60c49":{
      "scriptId":"u3"},
    "b60ecc845a7942fdaed96f838fb3ded0":{
      "scriptId":"u4"},
    "564bf7a9c43e478e87e995125ebb28e4":{
      "scriptId":"u5"},
    "e0b0311fd7714bff86e4843a6a75bfee":{
      "scriptId":"u6"},
    "dc8c50043e344caf88733074815996f1":{
      "scriptId":"u7"},
    "76e0d07a8e6f44b592d9c69b0eaae4ee":{
      "scriptId":"u8"},
    "77e6d82a19e74738a26f245ce49d6e07":{
      "scriptId":"u9"},
    "c9a202848db448ff9f568e6d5efb727c":{
      "scriptId":"u10"},
    "5af2d8bc27a64d299cfb0fa0bd040017":{
      "scriptId":"u11"},
    "c9ee3800379847d0b413cad1837a9d43":{
      "scriptId":"u12"},
    "6fc964ace8fb4cc7b5902ab4a374aaa6":{
      "scriptId":"u13"},
    "0aced7d1953c4746a1439aa1bb129bc0":{
      "scriptId":"u14"},
    "db056f410b884218bc7deab4fdb31f7e":{
      "scriptId":"u15"}}});